// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwgdayinyzueuqppsrgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3Z2RheWlueXp1ZXVxcHBzcmdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDc4ODYsImV4cCI6MjA3MzA4Mzg4Nn0.UJ5Y7YOICwDYs4Xs1kifJs7j4t3qAlBedSK2ILECChQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});