// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzpkqsqhdbkuwubqipfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6cGtxc3FoZGJrdXd1YnFpcGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mzg5MTUsImV4cCI6MjA3MzAxNDkxNX0.Exm-urENJ6EtpTY-Z2SlDpG3vYwhn65ZbzIlexemBMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});